# -*- mode: python -*-
# SCons build file

# Template originally downloaded from:
# <http://www.oxfordjournals.org/our_journals/bioinformatics/for_authors/bioinfo01.zip>

import os

# Inherit the current environment.
env = Environment(ENV=os.environ)

# Use LuaTeX instead of pdfTeX.
env.Replace(PDFLATEX='lualatex')

# Crash immediately on error.
env.AppendUnique(PDFLATEXFLAGS='-halt-on-error')

# Add shell escape for minted and dot2tex.
env.AppendUnique(PDFLATEXFLAGS='-shell-escape')

# Look in standard directory ~/texmf for .sty files.
env.SetDefault(TEXMFHOME=os.path.join(os.environ['HOME'], 'texmf'))

pdf = env.PDF('document.tex')
Default(pdf)
