# -*- mode: python -*-
# SCons build file

# Template originally downloaded from:
# <http://www.oxfordjournals.org/our_journals/bioinformatics/for_authors/bioinfo01.zip>

import os

env = Environment(ENV=os.environ)

# Look in standard directory ~/texmf for .sty files.
env['TEXMFHOME'] = os.path.join(os.environ['HOME'], 'texmf')

# Add shell escape for minted and dot2tex.
env.AppendUnique(PDFLATEXFLAGS='-shell-escape')

final_paper_pdf = env.PDF('document.tex')
Default(final_paper_pdf)
