# This is here just to remember how to create an image from the `dot'
# file. Graphviz and `dot' are required.

first: takai-jones-perl.png

takai-jones-perl.png: takai-jones-perl.dot
	dot -Tpng takai-jones-perl.dot -o takai-jones-perl.png
