# -*- mode: python -*-

import os


# Create Graphviz dot builders.
dot_builders = {}
for ext in ['png', 'svg']:
    builder = Builder(
        action='dot -T{0} $SOURCE -o $TARGET'.format(ext),
        suffix='.{0}'.format(ext),
        src_suffix='.dot')
    dot_builders['GraphvizDot{0}'.format(ext.upper())] = builder

# Inherit the current environment.
env = Environment(ENV=os.environ)

# Add dot builders to environment.
env.Append(BUILDERS=dot_builders)

png = env.GraphvizDotPNG('diagram')
svg = env.GraphvizDotSVG('diagram')
env.Default(svg)
